[package]
name = "sample_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
murmur3="0.5"
serde = {version="1.0",features=["derive"]}
serde_yaml = "0.9"
